'\" t
.\"     Title: ue4-docker-test
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2022-12-13
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "UE4\-DOCKER\-TEST" "1" "2022-12-13" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
ue4-docker-test \- run tests to verify the correctness of built container images
.SH "SYNOPSIS"
.sp
\fBue4\-docker test\fP \fItag\fP
.SH "DESCRIPTION"
.sp
This command runs a suite of tests to verify that built ue4\-full container images are functioning correctly and can be used to build and package Unreal projects and plugins.
.sp
This command is primarily intended for use by developers who are contributing to the ue4\-docker project itself.