FROM ubuntu:17.10

# Install our build prerequisites
RUN apt-get update && apt-get install -y --no-install-recommends \
	build-essential \
	ca-certificates \
	clang-5.0 \
	cmake \
	curl \
	git \
	python3 \
	python3-pip \
	tzdata \
	wget
