= Configuring Windows 10 and 11
:icons: font
:idprefix:
:idseparator: -
:source-highlighter: rouge
:toc:

== Warning

Windows 10 and 11 provide an optimal experience when running Windows containers, but **only when process isolation mode is used**.
Using https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/hyperv-container[Hyper-V isolation mode] will result in a suboptimal experience due to xref:windows-container-primer.adoc[several issues that impact performance and stability].
The default isolation mode depends on the specific version of Windows being used:

- Under Windows 10, Hyper-V isolation mode is the default isolation mode and https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/faq#can-i-run-windows-containers-in-process-isolated-mode-on-windows-10-[process isolation mode must be manually enabled] each time a container is built or run.
The xref:ue4-docker-build.adoc[ue4-docker build] command will automatically pass the flag to enable process isolation mode where possible. **This requires Windows 10 version 1809 or newer.**

- Under Windows 11, process isolation mode is the default isolation mode.

== Requirements

- 64-bit Windows 10 Pro, Enterprise, or Education (Version 1607 or newer)
- Hardware-accelerated virtualization enabled in the system BIOS/EFI
- Minimum 8GB of RAM
- Minimum 800GB available disk space for building container images

== Step 1: Install Docker CE for Windows

Download and install https://store.docker.com/editions/community/docker-ce-desktop-windows[Docker CE for Windows from the Docker Store].

== Step 2: Install Python 3 via Chocolatey

The simplest way to install Python and pip under Windows is to use the https://chocolatey.org/[Chocolatey package manager].
To do so, run the following command from an elevated PowerShell prompt:

[source,powershell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
----

You may need to restart your shell for it to recognise the updates that the Chocolatey installer makes to the system `PATH` environment variable.

Once these changes are recognised, you can install Python by running the following command from either an elevated PowerShell prompt or an elevated Command Prompt:

[source,powershell]
----
choco install -y python
----

== Step 3: Install ue4-docker

Install the ue4-docker Python package by running the following command from an elevated Command Prompt:

[source,powershell]
----
pip install ue4-docker
----

== Step 4: Manually configure Docker daemon settings

For building and running Windows containers:

- Configure the Docker daemon to https://docs.docker.com/desktop/windows/#switch-between-windows-and-linux-containers[use Windows containers] rather than Linux containers.
- Configure the Docker daemon to increase the maximum container disk size from the default 20GB limit by following https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#storage-limits[the instructions provided by Microsoft].
The 120GB limit specified in the instructions is not quite enough, so set a 400GB limit instead. **Be sure to restart the Docker daemon after applying the changes to ensure they take effect.**

WARNING: **The ue4-docker maintainers do not provide support for building and running Linux containers under Windows**, due to the various technical limitations of the Hyper-V and WSL2 backends for Docker Desktop (see https://github.com/adamrehn/ue4-docker/issues/205[this issue] for details of these limitations).
This functionality is still present in ue4-docker for those who choose to use it, but users are solely responsible for troubleshooting any issues they encounter when doing so.

For building and running Linux containers:

- Configure the Docker daemon to https://docs.docker.com/desktop/windows/#switch-between-windows-and-linux-containers[use Linux containers] rather than Windows containers.

- **If you are using the Hyper-V backend** then use https://docs.docker.com/desktop/windows/#resources[the Advanced section under the Resources tab of the Docker Desktop settings pane] to set the memory allocation for the Moby VM to 8GB and the maximum VM disk image size to 400GB.

- **If you are using the WSL2 backend** then https://docs.microsoft.com/en-us/windows/wsl/compare-versions#expanding-the-size-of-your-wsl-2-virtual-hard-disk[expand the WSL2 virtual hard disk] to at least 400GB.
