= ue4-docker-export (1)
:doctype: manpage
:icons: font
:idprefix:
:idseparator: -
:source-highlighter: rouge

== Name

ue4-docker-export - export components from built container image to the host system

== Synopsis

*ue4-docker export* _component_ _tag_ _destination_

This command can be used to export the following components:

== Description

=== Exporting Installed Builds under Linux

Installed Builds of Unreal Engine can be exported to the host system starting with version 4.21.0. Once you have built either the xref:available-container-images.adoc#ue4-minimal[ue4-minimal] or xref:available-container-images.adoc#ue4-full[ue4-full] image for the UE4 version that you want to export, you can export it to the host system like so:

[source,shell]
----
# Example: specify a version without a full image tag (assumes `adamrehn/ue4-full`)
# Exports the Installed Build from `adamrehn/ue4-full:4.27.0` to the directory `~/UnrealInstalled` on the host system
ue4-docker export installed "4.27.0" ~/UnrealInstalled
----

[source,shell]
----
# Example: specify a full image tag
# Exports the Installed Build from `adamrehn/ue4-minimal:4.27.0` to the directory `~/UnrealInstalled` on the host system
ue4-docker export installed "adamrehn/ue4-minimal:4.27.0" ~/UnrealInstalled
----

[source,shell]
----
# Example: use a container image based on ue4-minimal with a completely different tag
# Exports the Installed Build from `ghcr.io/epicgames/unreal-engine:dev-4.27.0` to the directory `~/UnrealInstalled` on the host system
ue4-docker export installed "ghcr.io/epicgames/unreal-engine:dev-4.27.0" ~/UnrealInstalled
----

=== Exporting Conan packages

The Conan wrapper packages generated by `conan-ue4cli` can be exported from the xref:available-container-images.adoc#ue4-full[ue4-full] image to the local Conan package cache on the host system like so:

[source,shell]
----
ue4-docker export packages 4.27.0 cache
----

https://conan.io/[Conan] will need to be installed on the host system for this to work.
To use the exported packages for development on the host system, you will also need to generate the accompanying profile-wide packages by running the command:

[source,shell]
----
ue4 conan generate --profile-only
----

This will require both `ue4cli` and `conan-ue4cli` to be installed on the host system.
