= Configuring Linux
:icons: font
:idprefix:
:idseparator: -
:source-highlighter: rouge
:toc:

== Requirements

- 64-bit version of one of Docker's https://docs.docker.com/install/#supported-platforms[supported Linux distributions] (CentOS 7+, Debian 7.7+, Fedora 26+, Ubuntu 14.04+)
- Minimum 8GB of RAM
- Minimum 400GB available disk space for building container images

== Step 1: Install Docker CE

Follow the official installation instructions from the Docker Documentation for your distribution:

- https://docs.docker.com/install/linux/docker-ce/centos/[CentOS]
- https://docs.docker.com/install/linux/docker-ce/debian/[Debian]
- https://docs.docker.com/install/linux/docker-ce/fedora/[Fedora]
- https://docs.docker.com/install/linux/docker-ce/ubuntu/[Ubuntu]

Once Docker is installed, follow the instructions from the https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user[Post-installation steps for Linux] page of the Docker Documentation to allow Docker commands to be run by a non-root user.
This step is required in order to enable audio support when performing cloud rendering using the NVIDIA Container Toolkit.

== Step 2: Install Python 3.6 or newer

WARNING: Note that older versions of these Linux distributions may not have Python 3.6 available in their system repositories by default.
When working with an older distribution it may be necessary to configure community repositories that provide newer versions of Python.

Under CentOS, run:

[source,shell]
----
sudo yum install python3 python3-devel python3-pip
----

Under Debian and Ubuntu, run:

[source,shell]
----
sudo apt-get install python3 python3-dev python3-pip
----

Under Fedora, run:

[source,shell]
----
sudo dnf install python3 python3-devel python3-pip
----

== Step 3: Install ue4-docker

Install the ue4-docker Python package by running the following command:

[source,shell]
----
sudo pip3 install ue4-docker
----

== Step 4: Use ue4-docker to automatically configure the Linux firewall

If the host system is running an active firewall that blocks access to port 9876 (required during the build of the xref:../building-images/available-container-images.adoc#ue4-source[ue4-source] image) then it is necessary to create a firewall rule to permit access to this port.
The xref:../commands/ue4-docker-setup.adoc[ue4-docker setup] command will detect this scenario and perform the appropriate firewall configuration automatically.
Simply run:

[source,shell]
----
sudo ue4-docker setup
----

Note that the `iptables-persistent` service will need to be installed for the newly-created firewall rule to persist after the host system reboots.
